source 'https://rubygems.org'

gem 'activesupport'
gem 'allure-cucumber'
gem 'eyes_selenium', '~> 4.6', '>= 4.6.1'
gem 'eyes_universal', '~> 3.3', '>= 3.3.1'
gem 'rake'
gem 'reek'
gem 'cucumber'
gem 'rspec'
gem 'rubocop'
gem 'ruby_raider', '~> 0.8.0'
gem 'selenium-webdriver'
